### ISSUE TITLE
Prediction masks for test images

### ISSUE THREAD

**Issue by d-misra** [gathierry/FastFlow#13]
Might it be possible to share some code for visualization of anomaly regions through heat map/masks from the trained model, on test images ?

**Comment by gathierry** [comment]
well, I don't have that part of the code. But I suppose you can render the color map from the output feature map in this line for example https://github.com/gathierry/FastFlow/blob/37c99ae33b8db0e5cb534fd0d197b0bc44817a03/main.py#L97 which shares the same size as input image (256x256).
