### ISSUE TITLE
Only one class present in y_true. ROC AUC score is not defined in that case..

### ISSUE THREAD

**Issue by linzengmin** [gathierry/FastFlow#16]
![@~_(EJX(DSF533U4SQ2H_ A](https://user-images.githubusercontent.com/49739150/187153749-8aa629be-c8b6-4e60-8fb8-5c2c21e5a233.png)

**Comment by founderlin** [comment]
There might be no image in the "good" dictionary.

**Comment by gathierry** [comment]
agree with @founderlin. Seems you only have one class in `y_true`, all 0 or all 1
