### ISSUE TITLE
Do the three categories(grid, screw and zipper) of a single channel need to add code to extend the channel from 1 to 3?

### ISSUE THREAD

**Issue by sehau** [gathierry/FastFlow#17]
Hello, Do the three categories of a single channel need to add code to extend the channel from 1 to 3?

When I'm using a single-channel class, such as Grid. There is an error like it.

> RuntimeError: Output with shape [1, 448, 448] doesn't match the broadcast shape [3, 448, 448]

I think adding a channel extension to dataset.py might solve this problem.

or using conversion functions `image = Image.open(image_file).convert('RGB')` in line 35 of dataset.py.

What do you think? Or am I going about it the wrong way?

**Comment by cytotoxicity8** [comment]
I guess the reason is the version of some packages.
Actually I noticed the error, so fixed the problem as the screenshot below. (See the commented code with #)

![image](https://user-images.githubusercontent.com/101567502/191042024-fe66011a-c946-4397-b2a0-8861e2bfca4a.png)

**Comment by sehau** [comment]
> I guess the reason is the version of some packages. Actually I noticed the error, so fixed the problem as the screenshot below. (See the commented code with #)
> 
> ![image](https://user-images.githubusercontent.com/101567502/191042024-fe66011a-c946-4397-b2a0-8861e2bfca4a.png)

Thanks for your reply. I got it.
