### ISSUE TITLE
Error occurred during validation.

### ISSUE THREAD

**Issue by leibaoer** [gathierry/FastFlow#19]
![image](https://user-images.githubusercontent.com/113488512/200981620-09890026-1f09-4b4d-a6fb-824654153404.png)

**Comment by leibaoer** [comment]
There is no modification of the code in datasets.But there is no picture of _mask.png in the test folder.

**Comment by gathierry** [comment]
Do you really have the image data under this folder?
As this is a Windows path, I'm not sure if it is recognized correctly by the program.

**Comment by leibaoer** [comment]
Make sure the data set is in good condition and can be trained, but the following shows that there is no mask picture in test. Shouldn't the mask picture be in groundtrue?

**Comment by leibaoer** [comment]
![image](https://user-images.githubusercontent.com/113488512/201048111-7156f777-f589-4925-813d-a53625320137.png)

**Comment by leibaoer** [comment]
Thanks for your reply.

**Comment by gathierry** [comment]
Maybe this line doesn't work in your code? I never tested on Windows but that might be the reason
https://github.com/gathierry/FastFlow/blob/37c99ae33b8db0e5cb534fd0d197b0bc44817a03/dataset.py#L44

**Comment by longge-vision** [comment]
You can modify the code to "image_file.replace("\\test\\", "\\ground_truth\\")" on windows
