### ISSUE TITLE
Can I/How to replace the resnet18 feature extractor by a MobileNetV3_large backbone?

### ISSUE THREAD

**Issue by Tekno-H** [gathierry/FastFlow#21]

**Comment by gathierry** [comment]
As this repo uses pretrained backbones from `timm`, you can simply replace the `backbone_name=resnet18` with `backbone_name=mobilenetv3_large_100` in config file.

You also need to extend this constant to get rid of the assertion error
https://github.com/gathierry/FastFlow/blob/37c99ae33b8db0e5cb534fd0d197b0bc44817a03/constants.py#L26
