### ISSUE TITLE
How to visualization the anomaly map?

### ISSUE THREAD

**Issue by Zigars** [gathierry/FastFlow#5]
I want use your code in my own dataset, but I do not know how to  visualization the anomaly map. 
So I can't see the detection results derectly. Can you give me some advice?

**Comment by gathierry** [comment]
basically, you just need to convert the output to a numpy array, then draw a heatmap with matplotlib

**Comment by Zigars** [comment]
Actually, the anomaly_map's datas are like this:
![image](https://user-images.githubusercontent.com/32835472/163110180-50c8947e-2ddf-4ff2-a1fc-d2a60ae386d1.png)

I don't know how to caculate this anomaly_map from a normalization flow, and the original paper doesn't mention how to get the anomaly_map, even loss function haven't mention either. I'm confuse about these problem.

**Comment by gathierry** [comment]
if this is your anomaly map then each value is the anomaly score for each pixel, just draw a heatmap of it
